name: Deploy to GCE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH agent
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan 35.201.205.104 >> ~/.ssh/known_hosts

      - name: Install dependencies
        run: npm install
        working-directory: ./web_ui

      - name: Build web_ui
        run: npm run build
        working-directory: ./web_ui

      - name: Deploy to GCE
        run: scp -r ./dist lcylcy66666@35.201.205.104:/home/lcylcy66666/aiwings/

      - name: Reload Nginx on GCE
        run: ssh lcylcy66666@35.201.205.104 "sudo service nginx reload"
